### PR TITLE
Tweak RGBLED tests - increases coverage

### PR DESCRIPTION
**Pull request by lurch**
...by a tiny amount ;)

### CODE REVIEW

**Comment by lurch** [comment]
@bennuttall Please don't merge PRs when the Travis-test fails! ;-)

**Comment by lurch** [comment]
@waveform80 Any idea why all the Python3 tests pass, but one of the Python2 tests fails? *Very* curious...

**Comment by bennuttall** [comment]
Oh I didn't realise...

**Comment by lurch** [comment]
Yeah, in the github UI it's unfortunately easy to mistake a Travis-fail because of a failing unit test (serious problem) for a Coverage-fail because of reduced code-coverage (minor problem)  :-/

**Comment by lurch** [comment]
As this PR has now been reverted, is there an easy way to 're-open' it, or do I need to create a new branch and submit a completely different PR from there?
https://github.com/RPi-Distro/python-gpiozero/compare/master...lurch:test_rgbled_tweaks doesn't work :-(

**Comment by bennuttall** [comment]
I'm not sure what's going on...

**Comment by lurch** [comment]
I already reverted it in #375 ... which is why #376 is empty.

**Comment by waveform80** [comment]
> @waveform80 Any idea why all the Python3 tests pass, but one of the Python2 tests fails? Very curious...

Wow ... that really is weird. My first thought is something fundamentally different in the GC between 2 and 3 ... I'll try and dig into it on Sunday (busy tomorrow with McrRaspJam, but I've got a little time on Sunday depending on how other stuff goes!).

**Comment by lurch** [comment]
> Wow ... that really is weird. My first thought is something fundamentally different in the GC between 2 and 3 ...

Just out of curiosity I even tried changing the failing test (`test_rgbled_initial_bad_value`) to use:
```python
    with pytest.raises(ValueError):
        with RGBLED(r, g, b, initial_value=(1.1, 0.2, 0.3)) as device:
            pass
    with pytest.raises(ValueError):
        with RGBLED(r, g, b, initial_value=(0.1, 1.2, 0.3)) as device:
            pass
```
but Python2.7 (in a local venv) still fails with exactly the same error `GPIOPinInUse: pin MOCK1 is already in use by another gpiozero object`  :-S  (and it still works in Python3.4)
And it's curious that `test_led_board_pwm_bad_initial_value` _does_ pass okay on Python2.7...

Have fun at McrRaspJam tomorrow! :-)

**Comment by lurch** [comment]
In a Python2.7 REPL...
```python
>>> from gpiozero.pins.mock import MockPWMPin
>>> import gpiozero.devices
>>> gpiozero.devices.pin_factory = MockPWMPin
>>> from gpiozero import *
>>> l = LEDBoard(4,5,6, pwm=True, initial_value=2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gpiozero/devices.py", line 123, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)
  File "gpiozero/boards.py", line 187, in __init__
    super(LEDBoard, self).__init__(*args, **kwargs)
  File "gpiozero/boards.py", line 117, in __init__
    for name, pin_or_collection in kwargs.items()
  File "gpiozero/boards.py", line 110, in <genexpr>
    for pin_or_collection in args
  File "gpiozero/devices.py", line 123, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)
  File "gpiozero/output_devices.py", line 301, in __init__
    raise OutputDeviceBadValue("initial_value must be between 0 and 1")
gpiozero.exc.OutputDeviceBadValue: initial_value must be between 0 and 1
>>> l = LEDBoard(4,5,6, pwm=True, initial_value=2)
Exception AttributeError: "'PWMLED' object has no attribute '_source_thread'" in  ignored
Exception AttributeError: AttributeError(u'no such attribute _source_thread',) in  ignored
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gpiozero/devices.py", line 123, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)
  File "gpiozero/boards.py", line 187, in __init__
    super(LEDBoard, self).__init__(*args, **kwargs)
  File "gpiozero/boards.py", line 117, in __init__
    for name, pin_or_collection in kwargs.items()
  File "gpiozero/boards.py", line 110, in <genexpr>
    for pin_or_collection in args
  File "gpiozero/devices.py", line 123, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)
  File "gpiozero/output_devices.py", line 301, in __init__
    raise OutputDeviceBadValue("initial_value must be between 0 and 1")
gpiozero.exc.OutputDeviceBadValue: initial_value must be between 0 and 1
>>> r = RGBLED(4,5,6, pwm=True, initial_value=(2,2,2))
Exception AttributeError: "'PWMLED' object has no attribute '_source_thread'" in  ignored
Exception AttributeError: AttributeError(u'no such attribute _source_thread',) in  ignored
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gpiozero/devices.py", line 123, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)
  File "gpiozero/output_devices.py", line 566, in __init__
    self.value = initial_value
  File "gpiozero/devices.py", line 147, in __setattr__
    return super(GPIOBase, self).__setattr__(name, value)
  File "gpiozero/output_devices.py", line 600, in value
    raise OutputDeviceBadValue('each RGB color component must be between 0 and 1')
gpiozero.exc.OutputDeviceBadValue: each RGB color component must be between 0 and 1
>>> r = RGBLED(4,5,6, pwm=True, initial_value=(2,2,2))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gpiozero/devices.py", line 123, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)
  File "gpiozero/output_devices.py", line 565, in __init__
    self._leds = tuple(LEDClass(pin, active_high) for pin in (red, green, blue))
  File "gpiozero/output_devices.py", line 565, in <genexpr>
    self._leds = tuple(LEDClass(pin, active_high) for pin in (red, green, blue))
  File "gpiozero/devices.py", line 123, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)
  File "gpiozero/output_devices.py", line 302, in __init__
    super(PWMOutputDevice, self).__init__(pin, active_high, initial_value=None)
  File "gpiozero/output_devices.py", line 41, in __init__
    super(OutputDevice, self).__init__(pin)
  File "gpiozero/mixins.py", line 69, in __init__
    super(SourceMixin, self).__init__(*args, **kwargs)
  File "gpiozero/devices.py", line 374, in __init__
    'pin %r is already in use by another gpiozero object' % pin
gpiozero.exc.GPIOPinInUse: pin MOCK4 is already in use by another gpiozero object
```

...and curiously, I get similar output in a Python3.4 REPL (which now **also** leaves me wondering how the unit-test was passing?!?)
```python
>>> from gpiozero.pins.mock import MockPWMPin
>>> import gpiozero.devices
>>> gpiozero.devices.pin_factory = MockPWMPin
>>> from gpiozero import *
>>> l = LEDBoard(4,5,6, pwm=True, initial_value=2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/devices.py", line 123, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/boards.py", line 187, in __init__
    super(LEDBoard, self).__init__(*args, **kwargs)
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/boards.py", line 117, in __init__
    for name, pin_or_collection in kwargs.items()
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/boards.py", line 110, in <genexpr>
    for pin_or_collection in args
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/devices.py", line 123, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/output_devices.py", line 301, in __init__
    raise OutputDeviceBadValue("initial_value must be between 0 and 1")
gpiozero.exc.OutputDeviceBadValue: initial_value must be between 0 and 1
>>> l = LEDBoard(4,5,6, pwm=True, initial_value=2)
Exception ignored in: Exception ignored in: Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/devices.py", line 123, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/boards.py", line 187, in __init__
    super(LEDBoard, self).__init__(*args, **kwargs)
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/boards.py", line 117, in __init__
    for name, pin_or_collection in kwargs.items()
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/boards.py", line 110, in <genexpr>
    for pin_or_collection in args
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/devices.py", line 123, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/output_devices.py", line 301, in __init__
    raise OutputDeviceBadValue("initial_value must be between 0 and 1")
gpiozero.exc.OutputDeviceBadValue: initial_value must be between 0 and 1
>>> r = RGBLED(4,5,6, pwm=True, initial_value=(2,2,2))
Exception ignored in: Exception ignored in: Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/devices.py", line 123, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/output_devices.py", line 566, in __init__
    self.value = initial_value
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/devices.py", line 147, in __setattr__
    return super(GPIOBase, self).__setattr__(name, value)
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/output_devices.py", line 600, in value
    raise OutputDeviceBadValue('each RGB color component must be between 0 and 1')
gpiozero.exc.OutputDeviceBadValue: each RGB color component must be between 0 and 1
>>> r = RGBLED(4,5,6, pwm=True, initial_value=(2,2,2))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/devices.py", line 123, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/output_devices.py", line 565, in __init__
    self._leds = tuple(LEDClass(pin, active_high) for pin in (red, green, blue))
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/output_devices.py", line 565, in <genexpr>
    self._leds = tuple(LEDClass(pin, active_high) for pin in (red, green, blue))
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/devices.py", line 123, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/output_devices.py", line 302, in __init__
    super(PWMOutputDevice, self).__init__(pin, active_high, initial_value=None)
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/output_devices.py", line 41, in __init__
    super(OutputDevice, self).__init__(pin)
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/mixins.py", line 69, in __init__
    super(SourceMixin, self).__init__(*args, **kwargs)
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/devices.py", line 374, in __init__
    'pin %r is already in use by another gpiozero object' % pin
gpiozero.exc.GPIOPinInUse: pin MOCK4 is already in use by another gpiozero object
```

....

Taking things one step further (and deactivating my venvs) I made a script called `gc_test.py` containing:
```python
from gpiozero.pins.mock import MockPWMPin
import gpiozero.devices
gpiozero.devices.pin_factory = MockPWMPin
from gpiozero import LEDBoard, RGBLED
try:
    l = LEDBoard(4,5,6, pwm=True, initial_value=2)
except Exception as e:
    print(e)

try:
    l = LEDBoard(4,5,6, pwm=True, initial_value=2)
except Exception as e:
    print(e)

try:
    r = RGBLED(4,5,6, pwm=True, initial_value=(2,2,2))
except Exception as e:
    print(e)

try:
    r = RGBLED(4,5,6, pwm=True, initial_value=(2,2,2))
except Exception as e:
    print(e)
```

If I then do `python2 -i gc_test.py` I get:
```python
initial_value must be between 0 and 1
Exception AttributeError: "'PWMLED' object has no attribute '_source_thread'" in  ignored
Exception AttributeError: AttributeError(u'no such attribute _source_thread',) in  ignored
initial_value must be between 0 and 1
Exception AttributeError: "'PWMLED' object has no attribute '_source_thread'" in  ignored
Exception AttributeError: AttributeError(u'no such attribute _source_thread',) in  ignored
each RGB color component must be between 0 and 1
pin MOCK4 is already in use by another gpiozero object
>>> 
```
and if I try creating another two bad-initial-value RGBLEDs:
```python
>>> r = RGBLED(4,5,6, pwm=True, initial_value=(2,2,2))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/devices.py", line 123, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/output_devices.py", line 566, in __init__
    self.value = initial_value
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/devices.py", line 147, in __setattr__
    return super(GPIOBase, self).__setattr__(name, value)
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/output_devices.py", line 600, in value
    raise OutputDeviceBadValue('each RGB color component must be between 0 and 1')
gpiozero.exc.OutputDeviceBadValue: each RGB color component must be between 0 and 1
>>> r = RGBLED(4,5,6, pwm=True, initial_value=(2,2,2))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/devices.py", line 123, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/output_devices.py", line 565, in __init__
    self._leds = tuple(LEDClass(pin, active_high) for pin in (red, green, blue))
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/output_devices.py", line 565, in <genexpr>
    self._leds = tuple(LEDClass(pin, active_high) for pin in (red, green, blue))
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/devices.py", line 123, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/output_devices.py", line 302, in __init__
    super(PWMOutputDevice, self).__init__(pin, active_high, initial_value=None)
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/output_devices.py", line 41, in __init__
    super(OutputDevice, self).__init__(pin)
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/mixins.py", line 69, in __init__
    super(SourceMixin, self).__init__(*args, **kwargs)
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/devices.py", line 374, in __init__
    'pin %r is already in use by another gpiozero object' % pin
gpiozero.exc.GPIOPinInUse: pin MOCK4 is already in use by another gpiozero object
```

Whereas if I instead repeat the above with `python3 -i gc_test.py` I get:
```python
initial_value must be between 0 and 1
initial_value must be between 0 and 1
each RGB color component must be between 0 and 1
each RGB color component must be between 0 and 1
Exception ignored in: Exception ignored in: Exception ignored in: Exception ignored in: >>> 
```
and creating the two bad RGBLEDs gives:
```python
>>> r = RGBLED(4,5,6, pwm=True, initial_value=(2,2,2))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/devices.py", line 123, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/output_devices.py", line 566, in __init__
    self.value = initial_value
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/devices.py", line 147, in __setattr__
    return super(GPIOBase, self).__setattr__(name, value)
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/output_devices.py", line 600, in value
    raise OutputDeviceBadValue('each RGB color component must be between 0 and 1')
gpiozero.exc.OutputDeviceBadValue: each RGB color component must be between 0 and 1
>>> r = RGBLED(4,5,6, pwm=True, initial_value=(2,2,2))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/devices.py", line 123, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/output_devices.py", line 565, in __init__
    self._leds = tuple(LEDClass(pin, active_high) for pin in (red, green, blue))
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/output_devices.py", line 565, in <genexpr>
    self._leds = tuple(LEDClass(pin, active_high) for pin in (red, green, blue))
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/devices.py", line 123, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/output_devices.py", line 302, in __init__
    super(PWMOutputDevice, self).__init__(pin, active_high, initial_value=None)
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/output_devices.py", line 41, in __init__
    super(OutputDevice, self).__init__(pin)
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/mixins.py", line 69, in __init__
    super(SourceMixin, self).__init__(*args, **kwargs)
  File "/home/andrew/github/lurch/python-gpiozero/gpiozero/devices.py", line 374, in __init__
    'pin %r is already in use by another gpiozero object' % pin
gpiozero.exc.GPIOPinInUse: pin MOCK4 is already in use by another gpiozero object
```

So it looks like perhaps theres a couple of things interacting in slightly different ways?
(dunno if any of this helps, but at least it gives you a more detailed starting point! ;-)  )
